title: "Utku Gülgeç"
subtitle: "An engineering notebook"

description: "A personal engineering notebook documenting hands-on exploration, experiments, and design thinking pursued independently alongside professional work."

url: "https://utkugulgec.github.io"
baseurl: ""

#remote_theme: "mmistakes/minimal-mistakes"

#plugins:
#  - jekyll-include-cache
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed
